import env from "./env.js";

const config = {
  NODE_ENV: env.NODE_ENV || "development",
  PORT: Number(env.PORT) || 5000,
  MONGO_URI: env.MONGO_URI,
  CLIENT_URL: env.CLIENT_URL || "http://localhost:3000",

  JWT_SECRET: env.JWT_SECRET,
  JWT_REFRESH_SECRET: env.JWT_REFRESH_SECRET,
  JWT_EXPIRE: env.JWT_EXPIRE || "15m",
  JWT_REFRESH_EXPIRE: env.JWT_REFRESH_EXPIRE || "7d",

  CLOUDINARY_NAME: env.CLOUDINARY_CLOUD_NAME || env.CLOUDINARY_NAME,
  CLOUDINARY_KEY: env.CLOUDINARY_API_KEY || env.CLOUDINARY_KEY,
  CLOUDINARY_SECRET: env.CLOUDINARY_API_SECRET || env.CLOUDINARY_SECRET,

  EMAIL: env.EMAIL || env.NODEMAILER_EMAIL,
  EMAIL_PASSWORD: env.EMAIL_PASSWORD || env.NODEMAILER_PASSWORD,
  CONTACT_ALERT_EMAIL: env.CONTACT_ALERT_EMAIL,

  ADMIN_EMAIL: env.ADMIN_EMAIL,
  ADMIN_PASSWORD: env.ADMIN_PASSWORD,
};

export default config;
